[package]
name = "speclang"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hcl-rs = "0.3.3"
serde = "1.0.137"
serde_json = "1.0.81"
wasm-bindgen = "0.2.80"

[profile.release]
opt-level = "s"
